name: netmadan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2a2a0'
    - '#ffffff'
    - '#83745f'
    - '#1c130e'
    - '#193d7a'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
